spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      #            ddl-auto: create-drop
      #            ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
        jdbc:
          batch_size: 100
          order_inserts: true
      format_sql: true
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
  mvc:
    contentnegotiation:
      favor-parameter: true
      favor-path-extension: true
      media-types:
        xls: application/vnd.ms-excel

logging.level:
  org.hibernate.SQL: debug

server:
  port: 8081

image:
  uploadPath: ./image/upload
  width: 160
  height: 160
  defaultUserImage: user2-160x160.jpg

file:
  uploadPath: ./file/upload

admin-api:
  store: /api/store
  coupon: /api/coupon
