server:
  port: 8882

spring:
  application:
    name: platform-api

  profiles:
    active: local

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lozm
    username: junlee
    password: password
    testQuery: "SELECT 1"
    hikari:
      maximum-pool-size: 5

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        default_batch_fetch_size: 500
        jdbc:
          batch_size: 100
          order_inserts: true
      format_sql: true

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        xls: application/vnd.ms-excel

logging:
  level:
    root: info
    lozm: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

image:
  uploadPath: ./image/upload
  width: 160
  height: 160
  defaultUserImage: user2-160x160.jpg