spring:
    datasource:
        driverClassName: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@//127.0.0.1:1521/XE
        username: system
        password: oracle
        testQuery: "SELECT 1 FROM DUAL"
        hikari:
            maximum-pool-size: 5
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        hibernate:
#            ddl-auto: create
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    batch_size: 100
                    order_inserts: true
            format_sql: true
        show-sql: true
        generate-ddl: true

server:
    port: 8082