spring:
    datasource:
        hikari:
            maximum-pool-size: 5
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                default_batch_fetch_size: 100
                jdbc:
                    batch_size: 100
                    order_inserts: true
            format_sql: true
        show-sql: true

server:
    port: 8082