server:
  port: 8080

spring:
  application:
    name: api-gateway-zuul

  profiles:
    active: local

logging:
  level:
    root: info

jwt:
  secret: hashing-jwt-token-secret-key-test
  expiration-time: 1800
  token-prefix: Bearer
  header-string: Authorization