server:
  port: 8882

spring:
  application:
    name: zuul-gateway-server

  profiles:
    active: local

logging:
  level:
    root: info
    lozm: debug

zuul:
  igoredServices: '*'
  routes:
    platform-api:
      path: /platorm-api/**
      serviceId: platform-api
      stripPrefix: true
    authentication-server:
      path: /authentication-server/**
      serviceId: authentication-server
      stripPrefix: true
  ws:
    brokerages:
      chatting-api:
        end-points: /lozm-chat
        brokers:  /topic
        destination-prefixes: /publish
  retryable: true
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true
    thread-pool-key-prefix: zuul-gateway-server